package com.example.shoppingapplication;

import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class MailSender {


        // Put recipient’s address
        String to = "berheaklilu1@gmail.com";
        Session session;
        // Put sender’s address
        String from = "berheaklilu1@gmail.com";
        final String username = "95519198077ee8";//username generated by Mailtrap
        final String password = "a878b7ca236907";//password generated by Mailtrap

        // Paste host address from the SMTP settings tab in your Mailtrap Inbox
        String host = "smtp.mailtrap.io";


    public MailSender() {
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "2525");// use one of the options in the SMTP settings tab in your Mailtrap Inbox
        session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });



        try {
            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);

            // Set From: header field
            message.setFrom(new InternetAddress(from));

            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject("Hello World!");

            // Put the content of your message
            message.setText("Hi here is your access token: 443rrt");


            // Send message
            Transport.send(message);



        } catch (MessagingException e) {
           e.printStackTrace();
        }

    }

    public boolean sendEmail (){
        try {
            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);

            // Set From: header field
            message.setFrom(new InternetAddress(from));

            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject("Hello World!");

            // Put the content of your message
            message.setText("Hi here is your access token: 443rrt");


            // Send message
            Transport.send(message);

            return true;

        } catch (MessagingException e) {
            return false;
        }

    }



}
