package com.example.shoppingapplication;

import java.security.AccessController;
import java.security.Provider;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class MailSender {


      /*  // Put recipient’s address
        String to = "berheaklilu1@gmail.com";
        Session session;
        // Put sender’s address
        String from = "berheaklilu1@gmail.com";*/
      static {
      }



    public MailSender() {

    }

    public boolean sendEmail (String toEmail, String subj,String msg){
        boolean check = false;
        String from = "berheaklilu1@gmail.com";
        String to = toEmail;
        final String username = "95519198077ee8";//username generated by Mailtrap
        final String password = "a878b7ca236907";//password generated by Mailtrap
        String host = "smtp.mailtrap.io";

        Properties props = new Properties();

        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");//it’s optional in Mailtrap
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", "465");// use one of the options in the SMTP settings tab in your Mailtrap Inbox
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });

        try {
            // Create a default MimeMessage object.
            Message message = new MimeMessage(session);

            // Set From: header field
            message.setFrom(new InternetAddress(from));

            // Set To: header field
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(to));

            // Set Subject: header field
            message.setSubject(subj);

            // Put the content of your message
            message.setText(msg);
            // Send message
            Transport.send(message);
            check =true;

        } catch (MessagingException e) {
            return false;
        }
       return check;
    }



}
